version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "phoenix"
    - dependency-name: "phoenix_html"
