version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  groups:
    mix-patches:
      patterns:
        - "*"
      update-types:
        - "patch"
  ignore:
    - dependency-name: heroicons
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
  groups:
    npm-patches:
      patterns:
        - "*"
      update-types:
        - "patch"
  ignore:
    - dependency-name: live_select
    - dependency-name: phoenix
    - dependency-name: phoenix_html
    - dependency-name: phoenix_live_react
    - dependency-name: phoenix_live_view
    - dependency-name: react-phoenix
