version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
  ignore:
    - dependency-name: live_select
    - dependency-name: phoenix
    - dependency-name: phoenix_html
    - dependency-name: phoenix_live_react
    - dependency-name: phoenix_live_view
    - dependency-name: react-phoenix
