# docker compose for running locally
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      # only for local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arrow_dev
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:

