name: Asana integration for GitHub PRs

on:
  workflow_dispatch:
  pull_request:
    types: [review_requested, closed, opened, reopened, converted_to_draft, edited, ready_for_review]
  pull_request_review:
    types: [submitted]

permissions:
  contents: read # needed to check out code
  pull-requests: read # needed to read PR metadata for Asana integration

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/asana.yml@ead2d40fcc0c546bd6f099a6d8fcd9f9950eab03 # v5.0.0
    with:
      development-section: "In Development"
      review-section: "Pending Review"
      merged-section: "Merged / Not Deployed"
      trigger-phrase: "\\*\\*Asana Ticket:\\*\\*"
      attach-pr: true
    secrets:
      asana-token: ${{ secrets.ASANA_PERSONAL_ACCESS_TOKEN }}
      github-secret: ${{ secrets.ASANA_GITHUB_INTEGRATION_SECRET }}
